
version: '3'

services:
  api:
    image: python:3.9-alpine
    ports:
      - "8000:8000"
    networks:
      - qrgen
    working_dir: /api
   
  front-end-nexjs:
    image: node:18-alpine
    ports: 
      - "3000:3000"
    Working_dir: /front-end-nexjs
    networks:
      - qrgen

