
version: '3'

services:
  api:
    container_name: apiimage
    image: python:3.9-alpine
    ports:
      - "8000:8000"
    networks:
      - qrgen
    working_dir: /api
   
  front-end-nexjs:
    container_name: frontendimage
    image: node:18-alpine
    ports: 
      - "3000:3000"
    working_dir: /front-end-nexjs
    networks:
      - qrgen

networks:
  qrgen:
    name: qrgen
    driver: bridge
    external: true

