version: '3'

services:
  api:
    container_name: apiimage
    build:
      context: /api
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    networks:
      - qrgen
    working_dir: /api
   
  front-end-nexjs:
    container_name: frontendimage
    build:
      context: /front-end-nextjs
      dockerfile: dockerfile
    ports: 
      - "3000:3000"
    working_dir: /front-end-nextjs
    networks:
      - qrgen

networks:
  qrgen:
    name: qrgen
    driver: bridge
    external: true

